### ISSUE TITLE
Torch 1.0.1 compatibility

### ISSUE THREAD

**Issue by sunggukcha** [tamakoji/pytorch-syncbn#3]
Hello tamakiji! I appreciate your implementation.

Can you update a branch for torch 1.0.1? Or if I can modify easily, then please let me know.

Thanks!
Sungguk Cha.

**Comment by tamakoji** [comment]
I do have my own but not pushed. It would take me a time to purge from my other codebase, since I am stuck in other things now.
But I would suggest trying weight standardization to deal with batch sizes (I haven't tried yet though).
https://github.com/joe-siyuan-qiao/WeightStandardization
